//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Web.Mvc;

namespace BRCTransport.Domain
{
    public partial class BillReportDTO
    {
        [DataMember()]
        public int BillId { get; set; }

        [DataMember()]
        public int BillNo { get; set; }

        [DataMember()]
        public DateTime BillDate { get; set; }

        [DataMember()]
        public Int32 CompanyId { get; set; }

        [DataMember()]
        public String BranchCode { get; set; }

        [DataMember()]
        public DateTime PaymentDueDate { get; set; }

        [DataMember()]
        public String BillType { get; set; }

        [DataMember()]
        public String BasicOfChargesGC { get; set; }

        [DataMember()]
        public String Enclosure { get; set; }

        [DataMember()]
        public String ServiceTaxThrough { get; set; }

        [DataMember()]
        public String CheckedBy { get; set; }

        [DataMember()]
        public int GrandTotal { get; set; }

        [DataMember()]
        public String CompanyName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String PhoneNo { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String ServiceTaxRegdNo { get; set; }

        [DataMember()]
        public String PolicyNo { get; set; }

        public double RecievePayment { get; set; }

        public double DueAmount { get; set; }
    }
}
