//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Web.Mvc;

namespace BRCTransport.Domain
{
    public partial class MRReportDTO
    {
        public Int32 MRId { get; set; }

        public Int32 MrNo { get; set; }

        public int BillId { get; set; }
        
        public DateTime MRDate { get; set; }
        
        public String LocationFrom { get; set; }

        public String LocationTo { get; set; }

        public Int32 BillNo { get; set; }

        public Double BillAmount { get; set; }

        public Double AmountRecieved { get; set; }

        public DateTime PaymentDueDate { get; set; }

        public String CompanyName { get; set; }

        public int CompanyId { get; set; }

        public DateTime BillDateObject { get; set; }

        public DateTime BillDate { get; set; }
    }
}
