//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblBillEntryDTO
    {
        [DataMember()]
        public int SrNo { get; set; }

        [DataMember()]
        public int BillOrderId { get; set; }

        [DataMember()]
        public Nullable<Int32> BillId { get; set; }

        [DataMember()]
        public String BookingOldBrCode { get; set; }

        [DataMember()]
        public String OldBillNo { get; set; }

        [DataMember()]
        public DateTime? OldBillDate { get; set; }

        [DataMember()]
        public String DestnCode { get; set; }

        [DataMember()]
        public String Particulars { get; set; }

        [DataMember()]
        [RegularExpression(@"^(|[1-9][0-9]*)$", ErrorMessage = "Charged amount must be number.")]
        public String ChargedWeight { get; set; }

        [DataMember()]
        [RegularExpression(@"^(|[1-9][0-9]*)$", ErrorMessage = "Rate must be number.")]
        public String Rate { get; set; }

        [DataMember()]
        [Required]
        [RegularExpression(@"^(|[1-9][0-9]*)$", ErrorMessage = "Amount must be number.")]
        public double Amount { get; set; }

        [DataMember()]
        public Int32 tblBill_BillNo { get; set; }

    }
}
