//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-12-13 - 19:32:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblBankMasterDTO
    {
        [DataMember()]
        public Int32 BankId { get; set; }

        [DataMember()]
        public String BankName { get; set; }

        [DataMember()]
        public String AccountNo { get; set; }

        [DataMember()]
        public String AccountType { get; set; }

        [DataMember()]
        public String Addrees { get; set; }

        [DataMember()]
        public String PhoneNo { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<Double> OpeningBalance { get; set; }

        [DataMember()]
        public Nullable<DateTime> OpeningDate { get; set; }

        [DataMember()]
        public List<Int32> tblBankTransactions_TransactionId { get; set; }
    }
}
