//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblChallanEntryDTO
    {
        [DataMember()]
        public int SrNo { get; set; }

        [DataMember()]
        public Int32 ChallanEntryNo { get; set; }

        [DataMember()]
        public Int32 ChallanId { get; set; }

        [DataMember()]
        public String BkgStnCode { get; set; }

        [DataMember()]
        public String CNNoWithAlphaCode { get; set; }

        [DataMember()]
        public String PackagesNos { get; set; }

        [DataMember()]
        public String PackagesMethod { get; set; }

        [DataMember()]
        public String SaidToContain { get; set; }

        [DataMember()]
        public String ActualWeightKgs { get; set; }

        [DataMember()]
        public String DestinationName { get; set; }

        [DataMember()]
        public Int32 tblChallan_ChallanNo { get; set; }
    }
}
