//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-12-13 - 19:32:48
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblCashAccountsMasterDTO
    {
        [DataMember()]
        public Int32 AccountId { get; set; }

        [DataMember()]
        public String AccountType { get; set; }

        [DataMember()]
        public String OpeningBalance { get; set; }

        [DataMember()]
        public Nullable<DateTime> OpeningDate { get; set; }

        [DataMember()]
        public Byte[] Description { get; set; }

    }
}
