//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblChallanDTO
    {
        [DataMember()]
        [Required]
        public Nullable<int> ChallanNo { get; set; }

        [DataMember()]
        public Int32 ChallanId { get; set; }

        [DataMember()]
        [Required]
        [Display(Name = "Challan Date")]
        public Nullable<DateTime> ChallanDateTime { get; set; }

        [DataMember()]
        [Required]
        public String VehicleNo { get; set; }

        [DataMember()]
        [Required]
        public String VehicleType { get; set; }

        [DataMember()]
        [Required]
        public String VechicleMake { get; set; }

        [DataMember()]
        public String VehicleModel { get; set; }

        [DataMember()]
        public String VehicleNoOfPointLoading { get; set; }

        [DataMember()]
        public String Vehicle4NoOfPointUnLoading { get; set; }

        [DataMember()]
        public String VehicleFleetCode { get; set; }

        [DataMember()]
        [Required]
        public String FromBrCode { get; set; }

        [DataMember()]
        [Required]
        public String LoadedForm { get; set; }

        [DataMember()]
        [Required]
        public String ToBrCode { get; set; }

        [DataMember()]
        public String Destination { get; set; }

        [DataMember()]
        public String DistanceKM { get; set; }

        [DataMember()]
        public String ScheduleDateofActual { get; set; }

        [DataMember()]
        public String VechicleEngineNo { get; set; }

        [DataMember()]
        public String VechicleChassisNo { get; set; }

        [DataMember()]
        public String DriverName { get; set; }

        [DataMember()]
        public String DriverMobileNo { get; set; }

        [DataMember()]
        public String DriverAddress { get; set; }

        [DataMember()]
        public String TaxTokenNo { get; set; }

        [DataMember()]
        public String TaxTokenNoValidUpto { get; set; }

        [DataMember()]
        public String TaxTokenNoIssuedFrom { get; set; }

        [DataMember()]
        public String DriverLicenseNo { get; set; }

        [DataMember()]
        public String LicenseIssuedFrom { get; set; }

        [DataMember()]
        public String LicenseValidUpto { get; set; }

        [DataMember()]
        public String RoadPermitNo { get; set; }

        [DataMember()]
        public String RoadPermitValidUpto { get; set; }

        [DataMember()]
        public String VechicleOwnerName { get; set; }

        [DataMember()]
        public String VechicleOwnerMobileNo { get; set; }

        [DataMember()]
        public String VechicleOwnerPanNo { get; set; }

        [DataMember()]
        public String VechicleOwnerAddress { get; set; }

        [DataMember()]
        public String InsPolicyNo { get; set; }

        [DataMember()]
        public String InsCoWithStn { get; set; }

        [DataMember()]
        public String VechicleEngagedByNameWithEmpCode1 { get; set; }

        [DataMember()]
        public String VechicleEngagedByNameWithEmpCode2 { get; set; }

        [DataMember()]
        public String VechicleAgentName { get; set; }

        [DataMember()]
        public String VechicleMobileNo { get; set; }

        [DataMember()]
        public String VechicleAgentAddress { get; set; }

        [DataMember()]
        public String VechicleFinancierDetails { get; set; }

        [DataMember()]
        public String BrokerLoadingAdviceNoDate { get; set; }

        [DataMember()]
        public double GrandTotalPKG { get; set; }

        [DataMember()]
        public double GrandTotalKGS { get; set; }

        [DataMember()]
        public String MaterialUnLoadingBy { get; set; }

        [DataMember()]
        public double PayableTotalPackages { get; set; }

        [DataMember()]
        public double PayableChargedWeight { get; set; }

        [DataMember()]
        public double PayableRatePerTon { get; set; }

        [DataMember()]
        public double TotalLorryHire { get; set; }

        [DataMember()]
        public double ITDSDeduction { get; set; }

        [DataMember()]
        public double PartyLorryHire { get; set; }

        [DataMember()]
        public double BalanceLorryHire { get; set; }

        [DataMember()]
        public List<Int32> tblChallanEntries_ChallanEntryNo { get; set; }

        public List<tblChallanEntryDTO> ChallanEntryList { get; set; }
    }
}
