//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblCompanyDTO
    {
        [DataMember()]
        public Int32 CompanyId { get; set; }

        [DataMember()]
        public String CompanyName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String PhoneNo { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String ServiceTaxRegdNo { get; set; }

        [DataMember()]
        public String PolicyNo { get; set; }

        [DataMember()]
        public List<Int32> tblConsignmentNotes_ConsignmentNoteNo { get; set; }

        public tblCompanyDTO()
        {
        }

        public tblCompanyDTO(Int32 companyId, String companyName, String address, String phoneNo, String description, String serviceTaxRegdNo, String policyNo, List<Int32> tblConsignmentNotes_ConsignmentNoteNo)
        {
			this.CompanyId = companyId;
			this.CompanyName = companyName;
			this.Address = address;
			this.PhoneNo = phoneNo;
			this.Description = description;
			this.ServiceTaxRegdNo = serviceTaxRegdNo;
			this.PolicyNo = policyNo;
			this.tblConsignmentNotes_ConsignmentNoteNo = tblConsignmentNotes_ConsignmentNoteNo;
        }
    }
}
