//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblLoginDTO
    {
        [DataMember()]
        public Int32 LoginId { get; set; }

        [DataMember()]
        public String LoginName { get; set; }

        [DataMember()]
        public String Password { get; set; }

        public tblLoginDTO()
        {
        }

        public tblLoginDTO(Int32 loginId, String loginName, String password)
        {
			this.LoginId = loginId;
			this.LoginName = loginName;
			this.Password = password;
        }
    }
}
