//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-12-14 - 15:51:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace BRCTransport.Domain
{
    [DataContract()]
    public partial class tblTransactionDTO
    {
        [DataMember()]
        public Int32 TransactionId { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "PLease select account name.")]
        [Display(Description = "Account")]
        public Int32 AccountId { get; set; }

        [DataMember()]
        public string AccountName { get; set; }

        [DataMember()]
        [Required]
        public DateTime TDate { get; set; }

        [DataMember()]
        public Double DrAmount { get; set; }

        [DataMember()]
        public Double CrAmount { get; set; }

        [DataMember()]
        [Required]
        public Double TransactionType { get; set; }

        [DataMember()]
        [Required]
        public Double Amount { get; set; }

        [DataMember()]
        public String Recievedby { get; set; }

        [DataMember()]
        public String PaidBy { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String ChequeNo { get; set; }

        [DataMember()]
        public DateTime? ChequeDate { get; set; }

        public List<tblAccountsMasterDTO> Accounts { get; set; }
    }
}
