//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BRCTransportDBEntities : DbContext
    {
        public BRCTransportDBEntities()
            : base("name=BRCTransportDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAccountsMaster> tblAccountsMasters { get; set; }
        public DbSet<tblBill> tblBills { get; set; }
        public DbSet<tblBillEntry> tblBillEntries { get; set; }
        public DbSet<tblChallan> tblChallans { get; set; }
        public DbSet<tblChallanEntry> tblChallanEntries { get; set; }
        public DbSet<tblCompany> tblCompanies { get; set; }
        public DbSet<tblConsignee> tblConsignees { get; set; }
        public DbSet<tblConsignmentNote> tblConsignmentNotes { get; set; }
        public DbSet<tblConsignor> tblConsignors { get; set; }
        public DbSet<tblLogin> tblLogins { get; set; }
        public DbSet<tblMRNote> tblMRNotes { get; set; }
        public DbSet<tblTransaction> tblTransactions { get; set; }
    }
}
