//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBill
    {
        public tblBill()
        {
            this.tblBillEntries = new HashSet<tblBillEntry>();
            this.tblMRNotes = new HashSet<tblMRNote>();
        }
    
        public int BillId { get; set; }
        public int BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> PartyId { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string BillType { get; set; }
        public string BasicOfChargesGC { get; set; }
        public string Enclosure { get; set; }
        public string ServiceTaxThrough { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<int> GrandTotal { get; set; }
        public string ServiceTaxRegdNo { get; set; }
    
        public virtual tblConsignor tblConsignor { get; set; }
        public virtual ICollection<tblBillEntry> tblBillEntries { get; set; }
        public virtual ICollection<tblMRNote> tblMRNotes { get; set; }
    }
}
