//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankTransaction
    {
        public int TransactionId { get; set; }
        public int BankId { get; set; }
        public System.DateTime TDate { get; set; }
        public string TType { get; set; }
        public double DrAmount { get; set; }
        public double CrAmount { get; set; }
        public string Description { get; set; }
    
        public virtual tblBankMaster tblBankMaster { get; set; }
    }
}
