//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillEntry
    {
        public int BillOrderId { get; set; }
        public Nullable<int> BillId { get; set; }
        public string BookingOldBrCode { get; set; }
        public string OldBillNo { get; set; }
        public Nullable<System.DateTime> OldBillDate { get; set; }
        public string DestnCode { get; set; }
        public string Particulars { get; set; }
        public string ChargedWeight { get; set; }
        public string Rate { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual tblBill tblBill { get; set; }
    }
}
