//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankMaster
    {
        public tblBankMaster()
        {
            this.tblBankTransactions = new HashSet<tblBankTransaction>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string Addrees { get; set; }
        public string PhoneNo { get; set; }
        public string Description { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
    
        public virtual ICollection<tblBankTransaction> tblBankTransactions { get; set; }
    }
}
