//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsignmentNote
    {
        public int ConsignmentId { get; set; }
        public Nullable<int> ConsignmentNoteNo { get; set; }
        public string CompanyName { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> CompanyDate { get; set; }
        public Nullable<double> CompanyAmount { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public Nullable<int> ConsignorId { get; set; }
        public string ConsigneeInvoiceNo { get; set; }
        public string ConsigneeServiceTaxRegNo { get; set; }
        public string ConsignorPurchaseOrderNo { get; set; }
        public string ConsignorServiceTaxRegNo { get; set; }
        public string FromCode { get; set; }
        public string ToCode { get; set; }
        public string NoofPackages { get; set; }
        public string MethodOfPacking { get; set; }
        public string ActualWtInKGS { get; set; }
        public string CategoryOfLoad { get; set; }
        public string Rate { get; set; }
        public string LoadType { get; set; }
        public string Distance { get; set; }
        public string KMS { get; set; }
        public string DescriptionSaidToContain { get; set; }
        public string PrivateMarketOtherIdentificaion { get; set; }
        public string BusinessType { get; set; }
        public string AdvancedPaymentMRNo { get; set; }
        public Nullable<System.DateTime> AdvancedPaymentDate { get; set; }
        public string AdvancedPaymentAmount { get; set; }
        public string DimensionLength { get; set; }
        public string DimensionWidth { get; set; }
        public string DimensionHeight { get; set; }
        public string DimensionNoOfPKGS { get; set; }
        public string DimensionTotalCFTCMT { get; set; }
        public string DimensionSinglePieceWeight { get; set; }
        public string DeclarationNo { get; set; }
        public string ValidUpto { get; set; }
        public string DeclaredValueOfGoods { get; set; }
        public string BasicOfBooking { get; set; }
        public string BilledWithMs { get; set; }
        public string BranchCode { get; set; }
        public string ToPay { get; set; }
        public string Rebooking { get; set; }
        public string MainConsignmentNo { get; set; }
        public string GoodRecievedDetails { get; set; }
        public string PanNo { get; set; }
        public string PartyCode { get; set; }
        public string ServicetaxThrough { get; set; }
        public string ValidType { get; set; }
        public string PhoneNo { get; set; }
        public string AddressofIssuing { get; set; }
        public Nullable<System.DateTime> ConsignmentDate { get; set; }
        public string CentralisedServiceTaxRegnNo { get; set; }
        public string CompanyPhone { get; set; }
        public string Charges1 { get; set; }
        public Nullable<double> Amount1 { get; set; }
        public string Charges2 { get; set; }
        public Nullable<double> Amount2 { get; set; }
        public string Charges3 { get; set; }
        public Nullable<double> Amount3 { get; set; }
        public string Charges4 { get; set; }
        public Nullable<double> Amount4 { get; set; }
        public string Charges5 { get; set; }
        public Nullable<double> Amount5 { get; set; }
        public Nullable<double> FinalAmount { get; set; }
        public string ServiceTaxisPayableBy { get; set; }
    
        public virtual tblConsignee tblConsignee { get; set; }
        public virtual tblConsignor tblConsignor { get; set; }
    }
}
