//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsignee
    {
        public tblConsignee()
        {
            this.tblConsignmentNotes = new HashSet<tblConsignmentNote>();
        }
    
        public int ConsigneeId { get; set; }
        public string ConsigneeName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string STNOCSTNO { get; set; }
        public string TINNOVATNO { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual ICollection<tblConsignmentNote> tblConsignmentNotes { get; set; }
    }
}
