//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChallan
    {
        public tblChallan()
        {
            this.tblChallanEntries = new HashSet<tblChallanEntry>();
        }
    
        public int ChallanId { get; set; }
        public Nullable<int> ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDateTime { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string VechicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleNoOfPointLoading { get; set; }
        public string Vehicle4NoOfPointUnLoading { get; set; }
        public string VehicleFleetCode { get; set; }
        public string FromBrCode { get; set; }
        public string LoadedForm { get; set; }
        public string ToBrCode { get; set; }
        public string Destination { get; set; }
        public string DistanceKM { get; set; }
        public string ScheduleDateofActual { get; set; }
        public string VechicleEngineNo { get; set; }
        public string VechicleChassisNo { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNo { get; set; }
        public string DriverAddress { get; set; }
        public string TaxTokenNo { get; set; }
        public string TaxTokenNoValidUpto { get; set; }
        public string TaxTokenNoIssuedFrom { get; set; }
        public string DriverLicenseNo { get; set; }
        public string LicenseIssuedFrom { get; set; }
        public string LicenseValidUpto { get; set; }
        public string RoadPermitNo { get; set; }
        public string RoadPermitValidUpto { get; set; }
        public string VechicleOwnerName { get; set; }
        public string VechicleOwnerMobileNo { get; set; }
        public string VechicleOwnerPanNo { get; set; }
        public string VechicleOwnerAddress { get; set; }
        public string InsPolicyNo { get; set; }
        public string InsCoWithStn { get; set; }
        public string VechicleEngagedByNameWithEmpCode1 { get; set; }
        public string VechicleEngagedByNameWithEmpCode2 { get; set; }
        public string VechicleAgentName { get; set; }
        public string VechicleMobileNo { get; set; }
        public string VechicleAgentAddress { get; set; }
        public string VechicleFinancierDetails { get; set; }
        public string BrokerLoadingAdviceNoDate { get; set; }
        public Nullable<double> GrandTotalPKG { get; set; }
        public Nullable<double> GrandTotalKGS { get; set; }
        public string MaterialUnLoadingBy { get; set; }
        public Nullable<double> PayableTotalPackages { get; set; }
        public Nullable<double> PayableChargedWeight { get; set; }
        public Nullable<double> PayableRatePerTon { get; set; }
        public Nullable<double> TotalLorryHire { get; set; }
        public Nullable<double> ITDSDeduction { get; set; }
        public Nullable<double> PartyLorryHire { get; set; }
        public Nullable<double> BalanceLorryHire { get; set; }
    
        public virtual ICollection<tblChallanEntry> tblChallanEntries { get; set; }
    }
}
