//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChallanEntry
    {
        public int ChallanEntryNo { get; set; }
        public Nullable<int> ChallanId { get; set; }
        public string BkgStnCode { get; set; }
        public string CNNoWithAlphaCode { get; set; }
        public string PackagesNos { get; set; }
        public string PackagesMethod { get; set; }
        public string SaidToContain { get; set; }
        public string ActualWeightKgs { get; set; }
        public string DestinationName { get; set; }
    
        public virtual tblChallan tblChallan { get; set; }
    }
}
