//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRNote
    {
        public int MRId { get; set; }
        public Nullable<int> MrNo { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<System.DateTime> MRDate { get; set; }
        public string RecievedFrom { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public string NoofPackages { get; set; }
        public string Weight { get; set; }
        public Nullable<double> AmountRecieved { get; set; }
        public string WayOfRecieve { get; set; }
        public Nullable<double> Fright { get; set; }
        public Nullable<double> StCharges { get; set; }
        public Nullable<double> Hamali { get; set; }
        public Nullable<double> Other1 { get; set; }
        public Nullable<double> Other2 { get; set; }
        public Nullable<double> Other3 { get; set; }
        public Nullable<double> Other4 { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual tblBill tblBill { get; set; }
    }
}
