//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRCTransport.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransactionId { get; set; }
        public int AccountId { get; set; }
        public System.DateTime TDate { get; set; }
        public double DrAmount { get; set; }
        public double CrAmount { get; set; }
        public string Recievedby { get; set; }
        public string PaidBy { get; set; }
        public string Description { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
    
        public virtual tblAccountsMaster tblAccountsMaster { get; set; }
    }
}
