//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-12-14 - 15:56:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using BRCTransport.Domain;
using BRCTransport.Database.ORM;

namespace BRCTransport.Domain
{

    /// <summary>
    /// Assembler for <see cref="tblAccountsMaster"/> and <see cref="tblAccountsMasterDTO"/>.
    /// </summary>
    public static partial class tblAccountsMasterAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblAccountsMasterDTO"/> converted from <see cref="tblAccountsMaster"/>.</param>
        static partial void OnDTO(this tblAccountsMaster entity, tblAccountsMasterDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblAccountsMaster"/> converted from <see cref="tblAccountsMasterDTO"/>.</param>
        static partial void OnEntity(this tblAccountsMasterDTO dto, tblAccountsMaster entity);

        /// <summary>
        /// Converts this instance of <see cref="tblAccountsMasterDTO"/> to an instance of <see cref="tblAccountsMaster"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblAccountsMasterDTO"/> to convert.</param>
        public static tblAccountsMaster ToEntity(this tblAccountsMasterDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblAccountsMaster();

            entity.AccountId = dto.AccountId;
            entity.AccountName = dto.AccountName;
            entity.AccountType = dto.AccountType;
            entity.AccountNo = dto.AccountNo;
            entity.Addrees = dto.Addrees;
            entity.PhoneNo = dto.PhoneNo;
            entity.OpeningBalance = dto.OpeningBalance;
            entity.OpeningDate = dto.OpeningDate;
            entity.Description = dto.Description;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblAccountsMaster"/> to an instance of <see cref="tblAccountsMasterDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblAccountsMaster"/> to convert.</param>
        public static tblAccountsMasterDTO ToDTO(this tblAccountsMaster entity)
        {
            if (entity == null) return null;

            var dto = new tblAccountsMasterDTO();

            dto.AccountId = entity.AccountId;
            dto.AccountName = entity.AccountName;
            dto.AccountType = entity.AccountType;
            if (Convert.ToInt32(dto.AccountType) == (int)AccountType.Bank)
            {
                dto.AccountTypeName = AccountType.Bank.ToString();
            }
            else
            {
                dto.AccountTypeName = AccountType.Cash.ToString();
            }
            dto.AccountNo = entity.AccountNo;
            dto.Addrees = entity.Addrees;
            dto.PhoneNo = entity.PhoneNo;
            dto.OpeningBalance = entity.OpeningBalance;
            dto.OpeningDate = entity.OpeningDate;
            dto.Description = entity.Description;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAccountsMasterDTO"/> to an instance of <see cref="tblAccountsMaster"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblAccountsMaster> ToEntities(this IEnumerable<tblAccountsMasterDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAccountsMaster"/> to an instance of <see cref="tblAccountsMasterDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblAccountsMasterDTO> ToDTOs(this IEnumerable<tblAccountsMaster> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
