//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/09/28 - 16:22:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using BRCTransport.Domain;
using BRCTransport.Database.ORM;

namespace BRCTransport.Domain
{

    /// <summary>
    /// Assembler for <see cref="tblChallan"/> and <see cref="tblChallanDTO"/>.
    /// </summary>
    public static partial class tblChallanAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblChallanDTO"/> converted from <see cref="tblChallan"/>.</param>
        static partial void OnDTO(this tblChallan entity, tblChallanDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblChallan"/> converted from <see cref="tblChallanDTO"/>.</param>
        static partial void OnEntity(this tblChallanDTO dto, tblChallan entity);

        /// <summary>
        /// Converts this instance of <see cref="tblChallanDTO"/> to an instance of <see cref="tblChallan"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblChallanDTO"/> to convert.</param>
        public static tblChallan ToEntity(this tblChallanDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblChallan();
            entity.ChallanId = dto.ChallanId;
            entity.ChallanNo = dto.ChallanNo;
            entity.ChallanDateTime = dto.ChallanDateTime;
            entity.VehicleNo = dto.VehicleNo;
            entity.VehicleType = dto.VehicleType;
            entity.VechicleMake = dto.VechicleMake;
            entity.VehicleModel = dto.VehicleModel;
            entity.VehicleNoOfPointLoading = dto.VehicleNoOfPointLoading;
            entity.Vehicle4NoOfPointUnLoading = dto.Vehicle4NoOfPointUnLoading;
            entity.VehicleFleetCode = dto.VehicleFleetCode;
            entity.FromBrCode = dto.FromBrCode;
            entity.LoadedForm = dto.LoadedForm;
            entity.ToBrCode = dto.ToBrCode;
            entity.Destination = dto.Destination;
            entity.DistanceKM = dto.DistanceKM;
            entity.ScheduleDateofActual = dto.ScheduleDateofActual;
            entity.VechicleEngineNo = dto.VechicleEngineNo;
            entity.VechicleChassisNo = dto.VechicleChassisNo;
            entity.DriverName = dto.DriverName;
            entity.DriverMobileNo = dto.DriverMobileNo;
            entity.DriverAddress = dto.DriverAddress;
            entity.TaxTokenNo = dto.TaxTokenNo;
            entity.TaxTokenNoValidUpto = dto.TaxTokenNoValidUpto;
            entity.TaxTokenNoIssuedFrom = dto.TaxTokenNoIssuedFrom;
            entity.DriverLicenseNo = dto.DriverLicenseNo;
            entity.LicenseIssuedFrom = dto.LicenseIssuedFrom;
            entity.LicenseValidUpto = dto.LicenseValidUpto;
            entity.RoadPermitNo = dto.RoadPermitNo;
            entity.RoadPermitValidUpto = dto.RoadPermitValidUpto;
            entity.VechicleOwnerName = dto.VechicleOwnerName;
            entity.VechicleOwnerMobileNo = dto.VechicleOwnerMobileNo;
            entity.VechicleOwnerPanNo = dto.VechicleOwnerPanNo;
            entity.VechicleOwnerAddress = dto.VechicleOwnerAddress;
            entity.InsPolicyNo = dto.InsPolicyNo;
            entity.InsCoWithStn = dto.InsCoWithStn;
            entity.VechicleEngagedByNameWithEmpCode1 = dto.VechicleEngagedByNameWithEmpCode1;
            entity.VechicleEngagedByNameWithEmpCode2 = dto.VechicleEngagedByNameWithEmpCode2;
            entity.VechicleAgentName = dto.VechicleAgentName;
            entity.VechicleMobileNo = dto.VechicleMobileNo;
            entity.VechicleAgentAddress = dto.VechicleAgentAddress;
            entity.VechicleFinancierDetails = dto.VechicleFinancierDetails;
            entity.BrokerLoadingAdviceNoDate = dto.BrokerLoadingAdviceNoDate;
            entity.GrandTotalPKG = dto.GrandTotalPKG;
            entity.GrandTotalKGS = dto.GrandTotalKGS;
            entity.MaterialUnLoadingBy = dto.MaterialUnLoadingBy;
            entity.PayableTotalPackages = dto.PayableTotalPackages;
            entity.PayableChargedWeight = dto.PayableChargedWeight;
            entity.PayableRatePerTon = dto.PayableRatePerTon;
            entity.TotalLorryHire = dto.TotalLorryHire;
            entity.ITDSDeduction = dto.ITDSDeduction;
            entity.PartyLorryHire = dto.PartyLorryHire;
            entity.BalanceLorryHire = dto.BalanceLorryHire;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblChallan"/> to an instance of <see cref="tblChallanDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblChallan"/> to convert.</param>
        public static tblChallanDTO ToDTO(this tblChallan entity)
        {
            if (entity == null) return null;

            var dto = new tblChallanDTO();

            dto.ChallanId = entity.ChallanId;
            dto.ChallanNo = entity.ChallanNo;
            dto.ChallanDateTime = entity.ChallanDateTime;
            dto.VehicleNo = entity.VehicleNo;
            dto.VehicleType = entity.VehicleType;
            dto.VechicleMake = entity.VechicleMake;
            dto.VehicleModel = entity.VehicleModel;
            dto.VehicleNoOfPointLoading = entity.VehicleNoOfPointLoading;
            dto.Vehicle4NoOfPointUnLoading = entity.Vehicle4NoOfPointUnLoading;
            dto.VehicleFleetCode = entity.VehicleFleetCode;
            dto.FromBrCode = entity.FromBrCode;
            dto.LoadedForm = entity.LoadedForm;
            dto.ToBrCode = entity.ToBrCode;
            dto.Destination = entity.Destination;
            dto.DistanceKM = entity.DistanceKM;
            dto.ScheduleDateofActual = entity.ScheduleDateofActual;
            dto.VechicleEngineNo = entity.VechicleEngineNo;
            dto.VechicleChassisNo = entity.VechicleChassisNo;
            dto.DriverName = entity.DriverName;
            dto.DriverMobileNo = entity.DriverMobileNo;
            dto.DriverAddress = entity.DriverAddress;
            dto.TaxTokenNo = entity.TaxTokenNo;
            dto.TaxTokenNoValidUpto = entity.TaxTokenNoValidUpto;
            dto.TaxTokenNoIssuedFrom = entity.TaxTokenNoIssuedFrom;
            dto.DriverLicenseNo = entity.DriverLicenseNo;
            dto.LicenseIssuedFrom = entity.LicenseIssuedFrom;
            dto.LicenseValidUpto = entity.LicenseValidUpto;
            dto.RoadPermitNo = entity.RoadPermitNo;
            dto.RoadPermitValidUpto = entity.RoadPermitValidUpto;
            dto.VechicleOwnerName = entity.VechicleOwnerName;
            dto.VechicleOwnerMobileNo = entity.VechicleOwnerMobileNo;
            dto.VechicleOwnerPanNo = entity.VechicleOwnerPanNo;
            dto.VechicleOwnerAddress = entity.VechicleOwnerAddress;
            dto.InsPolicyNo = entity.InsPolicyNo;
            dto.InsCoWithStn = entity.InsCoWithStn;
            dto.VechicleEngagedByNameWithEmpCode1 = entity.VechicleEngagedByNameWithEmpCode1;
            dto.VechicleEngagedByNameWithEmpCode2 = entity.VechicleEngagedByNameWithEmpCode2;
            dto.VechicleAgentName = entity.VechicleAgentName;
            dto.VechicleMobileNo = entity.VechicleMobileNo;
            dto.VechicleAgentAddress = entity.VechicleAgentAddress;
            dto.VechicleFinancierDetails = entity.VechicleFinancierDetails;
            dto.BrokerLoadingAdviceNoDate = entity.BrokerLoadingAdviceNoDate;
            dto.GrandTotalPKG = entity.GrandTotalPKG ?? 0;
            dto.GrandTotalKGS = entity.GrandTotalKGS ?? 0;
            dto.MaterialUnLoadingBy = entity.MaterialUnLoadingBy;
            dto.PayableTotalPackages = entity.PayableTotalPackages ?? 0;
            dto.PayableChargedWeight = entity.PayableChargedWeight ?? 0;
            dto.PayableRatePerTon = entity.PayableRatePerTon ?? 0;
            dto.TotalLorryHire = entity.TotalLorryHire ?? 0;
            dto.ITDSDeduction = entity.ITDSDeduction ?? 0;
            dto.PartyLorryHire = entity.PartyLorryHire ?? 0;
            dto.BalanceLorryHire = entity.BalanceLorryHire ?? 0;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblChallanDTO"/> to an instance of <see cref="tblChallan"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblChallan> ToEntities(this IEnumerable<tblChallanDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblChallan"/> to an instance of <see cref="tblChallanDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblChallanDTO> ToDTOs(this IEnumerable<tblChallan> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
